### ISSUE TITLE
Abstracción Facultad (como controlador)

### ISSUE THREAD

**Issue by cai-uba** [rlafitte/CAI_877071_Facultad#1]
La abstracción Facultad, es quién maneja y realiza los algoritmos para manejar los cambios de su estado (agregaciones de alumnos y empleados).
Lo ideal es que quede desacoplada y lista para poder ser usada en otros proyectos.
El planteo no está mal pero en caso de necesitar hacer este proyecto en un Windows Forms, habría que rehacer la clase Facultad.
Intená rehacerla en la librería y en el program solo metodos modularizados que hagan los enlaces entre Facultad - Alumno y Empleado.

**Comment by rlafitte** [comment]
Gente, cómo están?
Ahí lo estuve arreglando un poco, todavía no lo pude terminar pero ya tengo la librería Controlador por separado. Si le pueden dar un vistazo les agradezco (lo probé y funciona, pero más que nada tema sintaxis si hay algo desprolijo).
Para el parcial lo voy a tener en cuenta. Gracias!
